###### To solve a puzzle, you are given an initial state and a goal state.
###### Target is to reach goal state from initial state using puzzle rules.
######  We can move blank tile only on left, right, up, and down
![Capture.JPG](attachment:Capture.JPG)

# Generate an intial state of NPuzzle

In [1]:
import numpy as np
import random
def get_state(N):    
    state = [item for item in range(N*N)]# [0,1,2,...,15]
    #print(state)
    random.shuffle(state)
    #print(state)
    tmp = np.array(state)
    print(tmp.reshape(N,N))
    return state

In [2]:
get_state(3)

[[4 5 8]
 [1 7 2]
 [0 6 3]]


[4, 5, 8, 1, 7, 2, 0, 6, 3]

# Calculate inversion

Inversion is a pair of tiles that are in the reverse order from where they ought to be. In our case, the bigger number is in front of the smaller one.



![Capture.JPG](attachment:Capture.JPG)

In [3]:
def count_inversion(state):
    #arr = [i for i in arr if i !=0]
    print(state)
    inversion = []
    for i in range(len(state)):    
        count = 0
        for j in range(i+1,len(state)):        
            if state[i] > state[j]: 
                count = count + 1
        inversion.append(count)
    #print(inversion)
    return sum(inversion)

In [36]:
s = get_state(4)
count_inversion(s)

[[12  3  9  7]
 [10  6 11  1]
 [ 5 13  2 14]
 [15  4  0  8]]
[12, 3, 9, 7, 10, 6, 11, 1, 5, 13, 2, 14, 15, 4, 0, 8]


63

# **Find blank row**

In [37]:
# find row position of the blank tile
import math

def get_blank_row(state):
  n = int(math.sqrt(len(state)))
  return n - state.index(0) // n
  # r = math.floor(math.sqrt(len(state)))
  # for i in range(0, r):
  #   for j in range(i * r, (i * r) + r):
  #     if(state[j] == 0):
  #       return i
    # for column in row:
      # if(state[row][column]): print(row, column) 

get_blank_row(s)

1

# Solvability Rules

In [48]:
# apply the rules to decide solvability
#  N, I, R
# define a method to return solvability (input S)
# return True if solvable or False if not

def isSolvable(initialState):
  N = int(math.sqrt(len(initialState)))
  I = count_inversion(initialState)
  R = get_blank_row(initialState)
  # decide solvability
  print(N, I, R)
  if(N % 2 != 0 and I % 2 == 0): return True
  if(N % 2 == 0 and I % 2 == 0 and R % 2 != 0): return True
  if(N % 2 == 0 and I % 2 != 0 and R % 2 == 0): return True
  return False
  


In [67]:
while(True):
  S = get_state(5)
  if isSolvable(S): break


[[16  5 17  1 14]
 [ 8 20  7 21  2]
 [13  9 22  0  4]
 [24 10  6 15 12]
 [23 19 11 18  3]]
[16, 5, 17, 1, 14, 8, 20, 7, 21, 2, 13, 9, 22, 0, 4, 24, 10, 6, 15, 12, 23, 19, 11, 18, 3]
5 137 3
[[ 0  8 22 13 11]
 [19  5  4 23 12]
 [15 24 14  3  7]
 [ 2 17 20  9  6]
 [ 1 18 16 21 10]]
[0, 8, 22, 13, 11, 19, 5, 4, 23, 12, 15, 24, 14, 3, 7, 2, 17, 20, 9, 6, 1, 18, 16, 21, 10]
5 143 5
[[15  3  6 17  9]
 [ 0 10 22 21 14]
 [19 16 20  5 18]
 [ 4 13  8 23 24]
 [ 7 11  2 12  1]]
[15, 3, 6, 17, 9, 0, 10, 22, 21, 14, 19, 16, 20, 5, 18, 4, 13, 8, 23, 24, 7, 11, 2, 12, 1]
5 156 4
